### ISSUE TITLE
Create favorite connections list

### ISSUE THREAD

**Issue by MBeggiato** [MBeggiato/Flow.Launcher.Plugin.RDP#1]
## What
Implement a system to favorite certain connections, so they get displayed on the top.
This could be implemented using the `score` parameter of results.
## Difficulty
Should be easy to implement, as settings functionality is already implemented on a rudimentary basis.
## Resources
See [this](https://www.flowlauncher.com/docs/#/API-Reference/Flow.Launcher.Plugin/Result/Score) for the `score` parameter.

**Comment by Laxynium** [comment]
Hi, could I take this one?

**Comment by MBeggiato** [comment]
> Hi, could I take this one?
> 
> 
> 
> 

Sure thing ! I'll assign you.

**Comment by MBeggiato** [comment]
@Laxynium thank you!
